In [1]:
# TENSORFLOW
import tensorflow as tf
import numpy as np

In [2]:
a=tf.constant(15)
b=tf.constant(20)
print(a*b)

tf.Tensor(300, shape=(), dtype=int32)


In [3]:
x=np.random.rand(100).astype(np.float32)
print(x)

[0.6255894  0.76211894 0.4923908  0.5984841  0.43553367 0.86361814
 0.5258384  0.37507215 0.2786291  0.7880572  0.6691819  0.6044925
 0.39970753 0.9344519  0.6262323  0.34627104 0.90268314 0.6361491
 0.6846697  0.6586219  0.18961722 0.98863024 0.33329657 0.5982643
 0.50581175 0.8394036  0.08170426 0.915101   0.49758214 0.42208257
 0.42355785 0.04261615 0.46261802 0.9285579  0.4797071  0.6023995
 0.07636965 0.16722144 0.3908249  0.20535909 0.6936247  0.37095916
 0.10640281 0.42078808 0.15860353 0.15050113 0.39302424 0.40298757
 0.4360927  0.8152559  0.9742102  0.28507593 0.14162315 0.11221021
 0.44589218 0.09234221 0.95445955 0.45937943 0.5288144  0.60429144
 0.48132417 0.1873742  0.7929383  0.7896797  0.12404459 0.39618376
 0.49186137 0.5406069  0.00939533 0.63355    0.1452465  0.8707016
 0.7951499  0.62605727 0.18518063 0.73761857 0.8757402  0.31258026
 0.99742395 0.33613566 0.507949   0.5657874  0.41976994 0.89915437
 0.4265355  0.41291788 0.28061143 0.99488556 0.71508205 0.392934
 0

In [4]:
y=0.2*x+0.2

In [5]:
W=tf.Variable(tf.random.normal([1]))

In [6]:
b=tf.Variable(tf.zeros([1]))

In [7]:
def mse_loss():
    y_pred=W*x+b
    loss=tf.reduce_mean(tf.square(y_pred-y))
    return loss

In [8]:
optimizer=tf.optimizers.Adam()

In [12]:
for step in range(5000):
    with tf.GradientTape() as tape:
        loss = mse_loss()  # Call your loss function here

    # Compute gradients of loss with respect to variables [W, b]
    gradients = tape.gradient(loss, [W, b])

    # Apply gradients to update W and b
    optimizer.apply_gradients(zip(gradients, [W, b]))

    # Print the progress every 500 steps
    if step % 500 == 0:
        print(step, W.numpy(), b.numpy())

0 [2.0605392] [-0.00099999]
500 [1.6612548] [-0.36247945]
1000 [1.4352438] [-0.43183473]
1500 [1.257383] [-0.3602431]
2000 [1.0690656] [-0.2605003]
2500 [0.8748727] [-0.15704107]
3000 [0.68904734] [-0.0583755]
3500 [0.52493] [0.0285081]
4000 [0.39306283] [0.09817103]
4500 [0.29914072] [0.14772618]


In [13]:
# PYTORCH
import torch
import numpy as np

In [15]:
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))

<class 'torch.Tensor'>


In [16]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [17]:
print(x_np)


tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [18]:
print(type(x_np))

<class 'torch.Tensor'>


In [19]:
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)


One Tensor: 
 tensor([[1, 1],
        [1, 1]])


In [20]:
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[0.6665, 0.5033],
        [0.6944, 0.0262]])


In [21]:
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))

tensor([[0.7573, 0.7606, 0.3027],
        [0.1259, 0.8803, 0.1669]])
<class 'torch.Tensor'>


In [22]:
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>


In [23]:
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))

tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>


In [54]:
tensor = torch.rand(3,4)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.7662, 0.0429, 0.7482, 0.1534],
        [0.0964, 0.0726, 0.1697, 0.8039],
        [0.4114, 0.7444, 0.2247, 0.2773]])
torch.Size([3, 4])
torch.float32
cpu


In [55]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print("Device tensor is stored in ", tensor.device)

In [57]:
tensor = torch.ones(4,4)
print(tensor)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [58]:
tensor1 = torch.zeros(4,4)
print(tensor1)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [59]:
tensor2 = torch.cat([tensor,tensor1])
print(tensor2)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [64]:
tensor.mul(tensor1)
tensor * tensor1
tensor.T

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])

In [65]:
tensor.add_(3)
print(tensor)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [66]:
t = torch.ones(5)
print(t)

tensor([1., 1., 1., 1., 1.])


In [67]:
n = t.numpy()
print(n)
print(type(n))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
